### PR TITLE
Get rid of deprecated ViewPropTypes, etc

### LINKED ISSUE #131: ViewPropTypes' is not supported in 'react-native-web' v12.0 onwards
If you upgrade to RNW 12.0 or greater you can no longer use react native web 

Error: ./node_modules/react-native-table-component/components/rows.js
Cannot find module: 'react-native-web/dist/exports/ViewPropTypes'. Make sure this package is installed.

### PR DESCRIPTION
**Pull request by AndyHubert**
Fixes #131

### CODE REVIEW

**Comment by markybry** [comment]
Please can this be reviewed and merged asap

**Comment by vjsingh** [comment]
Agreed, please merge

**Review by osamaasifoak — APPROVED** [review]

**Comment by osamaasifoak** [comment]
Merge this PR for removing TypeError: Cannot read property 'style' of undefined in WEB.

**Comment by leocaseiro** [comment]
hey @Gil2015 can you please publish these changes?
https://github.com/necolas/react-native-web/issues/1537

Otherwise, as an MIT license, can someone publish this version to npm? I'm, happy to do it myself.

**Review by Chaitra9225 — APPROVED** [review]

**Comment by Gil2015** [comment]
merge #138

**Pull request merged**
