### PR TITLE
Converted to Typescript

### PR DESCRIPTION
**Pull request by m4ttheweric**
Not sure if this will be approved, but I went through and re-wrote this using Typescript.

Cheers,

Matt

### CODE REVIEW

**Comment by m4ttheweric** [comment]
Also updated most relevant major packages.

**Review by Gil2015 — APPROVED** [review]

**Comment by m4ttheweric** [comment]
Thanks for the PR approval! Hope it helps others!

**Review by Yuri-Tiofilo — APPROVED** [review]
I was having problems with typescript in this lib, I believe this PR is correct and that it can be merged into the original lib

**Comment by m4ttheweric** [comment]
Just curious if this can be merged or closed. Doing some housekeeping on my PRs and wanting to clear stuff out.

**Comment by m4ttheweric** [comment]
I am going to go ahead and close this since I haven't heard back from anyone!

**Pull request closed without merging**
